/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DataAccessObj.LopDAO;
import DataAccessObj.SinhVienDAO;
import Model.LopHoc;
import Model.SinhVien;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS RG
 */
public class formMain extends javax.swing.JFrame {
   

    /**
     * Creates new form formMain
     */
    public void LoadData()
    {       
        //Do du lieu vao combobox
        LopDAO lhDAO = new LopDAO();
        Vector<LopHoc> vec = lhDAO.DanhSachLop();
 //       List<String> tenLop = new ArrayList<>();

        DefaultComboBoxModel cbb = new DefaultComboBoxModel();
        for (LopHoc lh : vec) 
        {
            cbb.addElement(lh);
        }
        cbbMaLop.setModel(cbb);
        
        //Do du lieu vao table
        SinhVienDAO svDAO = new SinhVienDAO();
        ArrayList<SinhVien> arrSV = svDAO.DanhSachSinhVien();
        DefaultTableModel tableSV = (DefaultTableModel) this.tableSV.getModel();
            tableSV.setRowCount(0);
        for(SinhVien sv : arrSV)
        {
            Object[] row = new Object[]{sv.getId(),sv.getName(),sv.getGenDer(),sv.getEmail(),sv.getBirthDay(),sv.getIdClass()};
            tableSV.addRow(row);
        }
        int sl = tableSV.getRowCount();
        txtSoLuongSV.setText(String.valueOf(sl));
           
    }
    
    
    
    public formMain() {
        initComponents();
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSV = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        lbThongTinSV = new javax.swing.JLabel();
        lbSoLuongSV = new javax.swing.JLabel();
        txtSoLuongSV = new javax.swing.JTextField();
        cbbMaLop = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lbMSSV = new javax.swing.JLabel();
        lbTTSV = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        lbHoTen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHoTen = new javax.swing.JTextPane();
        lbGioiTinh = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtEmail = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNgaySinh = new javax.swing.JTextPane();
        lbMaLop = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();
        checkboxNam = new javax.swing.JCheckBox();
        checkboxNu = new javax.swing.JCheckBox();
        btnReLoad = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        itemDangXuat = new javax.swing.JMenuItem();
        itemThoat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cửa Sổ Chính");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Họ Tên", "Giới Tính", "Email", "Ngày Sinh", "Mã lớp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSV);
        if (tableSV.getColumnModel().getColumnCount() > 0) {
            tableSV.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableSV.getColumnModel().getColumn(2).setPreferredWidth(20);
            tableSV.getColumnModel().getColumn(5).setPreferredWidth(25);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 542, 470));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 454, 78, -1));

        btnXoa.setText("Xóa");
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 454, 83, -1));

        btnCapNhat.setText("Cập Nhật");
        getContentPane().add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 454, 88, -1));

        lbThongTinSV.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbThongTinSV.setText("QUẢN LÝ SINH VIÊN KHOA CNTT");
        getContentPane().add(lbThongTinSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 310, -1));

        lbSoLuongSV.setText("Số lượng sinh viên:");
        getContentPane().add(lbSoLuongSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 556, -1, -1));

        txtSoLuongSV.setEditable(false);
        getContentPane().add(txtSoLuongSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 553, 82, -1));

        cbbMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaLopActionPerformed(evt);
            }
        });
        getContentPane().add(cbbMaLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 90, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        lbMSSV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbMSSV.setText(" Mã Số :");

        lbTTSV.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lbTTSV.setText("Thông tin sinh viên");

        lbHoTen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbHoTen.setText("Họ Tên:");

        jScrollPane2.setViewportView(txtHoTen);

        lbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbGioiTinh.setText("Giới Tính:");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbEmail.setText("Email :");

        lbNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbNgaySinh.setText("Ngày Sinh:");

        jScrollPane3.setViewportView(txtEmail);

        jScrollPane4.setViewportView(txtNgaySinh);

        lbMaLop.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbMaLop.setText("Mã Lớp:");

        checkboxNam.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        checkboxNam.setText("Nam");

        checkboxNu.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        checkboxNu.setText("Nữ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbMaLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbGioiTinh)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lbHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbMSSV, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                            .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(checkboxNam, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                                    .addComponent(txtMSSV)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbNgaySinh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkboxNu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbTTSV, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTTSV)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMSSV)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbHoTen)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGioiTinh)
                            .addComponent(checkboxNam)
                            .addComponent(checkboxNu))
                        .addGap(32, 32, 32)
                        .addComponent(lbEmail))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaLop)
                    .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 300, 370));

        btnReLoad.setText("Reload");
        btnReLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReLoadActionPerformed(evt);
            }
        });
        getContentPane().add(btnReLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 70, -1));

        jMenu2.setText("Hệ Thống");

        itemDangXuat.setText("Đăng xuất");
        itemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDangXuatActionPerformed(evt);
            }
        });
        jMenu2.add(itemDangXuat);

        itemThoat.setText("Thoát");
        itemThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemThoatActionPerformed(evt);
            }
        });
        jMenu2.add(itemThoat);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaLopActionPerformed
        SinhVienDAO svDAO = new SinhVienDAO();
        ArrayList<SinhVien> arrSV = svDAO.DanhSachSinhVienTheoLop(cbbMaLop.getSelectedItem().toString());
        DefaultTableModel tableSV = (DefaultTableModel) this.tableSV.getModel();
            tableSV.setRowCount(0);
        for(SinhVien sv : arrSV)
        {
            Object[] row = new Object[]{sv.getId(),sv.getName(),sv.getGenDer(),sv.getEmail(),sv.getBirthDay(),sv.getIdClass()};
            tableSV.addRow(row);
        }
        int sl = tableSV.getRowCount();
        txtSoLuongSV.setText(String.valueOf(sl));
    }//GEN-LAST:event_cbbMaLopActionPerformed

    private void btnReLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReLoadActionPerformed
        // TODO add your handling code here:
        LoadData();
        txtMSSV.setText("");
        txtEmail.setText("");
        txtHoTen.setText("");
        txtNgaySinh.setText("");
        txtMSSV.setText("");
        txtMaLop.setText("");
        checkboxNam.setSelected(false);
        checkboxNu.setSelected(false);
    }//GEN-LAST:event_btnReLoadActionPerformed

    private void itemThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemThoatActionPerformed
        if (JOptionPane.showConfirmDialog(null,
                "Bạn có chắc chắn muốn đóng ứng dụng?", "Thoát?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemThoatActionPerformed

    private void itemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDangXuatActionPerformed
        this.dispose();
        formDangNhap a = new formDangNhap();
        a.setVisible(true);
    }//GEN-LAST:event_itemDangXuatActionPerformed

    private void tableSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSVMouseClicked

        txtMSSV.setText(tableSV.getValueAt(tableSV.getSelectedRow(), 0).toString());
        txtHoTen.setText(tableSV.getValueAt(tableSV.getSelectedRow(), 1).toString());
        
        String gender = "Nam";
        if(gender.equals(tableSV.getValueAt(tableSV.getSelectedRow(), 2).toString()))
        {
            checkboxNam.setSelected(true);
            checkboxNu.setSelected(false);
        }
        else
        {
            checkboxNu.setSelected(true);
            checkboxNam.setSelected(false);
        }
            
        txtEmail.setText(tableSV.getValueAt(tableSV.getSelectedRow(), 3).toString());
        txtNgaySinh.setText(tableSV.getValueAt(tableSV.getSelectedRow(), 4).toString());
        txtMaLop.setText(tableSV.getValueAt(tableSV.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_tableSVMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if (((("".equals(txtMSSV.getText()) || "".equals(txtHoTen.getText()))
                || "".equals(txtNgaySinh.getText())) || "".equals(txtEmail.getText())) || "".equals(txtMaLop.getText())) {
            JOptionPane.showMessageDialog(null, "Yều cầu nhập đầy đủ thông tin!", "Cảnh Báo!",
                    JOptionPane.WARNING_MESSAGE);
        }

        SinhVienDAO svDAO = new SinhVienDAO();
        SinhVien a = new SinhVien();
        a.setId(Integer.parseInt(txtMSSV.getText()));
        a.setName(txtHoTen.getText());
        if (checkboxNam.isSelected()) {
            a.setGenDer(checkboxNam.getText());
        } else {
            a.setGenDer(checkboxNu.getText());
        }
        a.setBirthDay(txtNgaySinh.getText());
        a.setEmail(txtEmail.getText());
        a.setIdClass(txtMaLop.getText());
        
        //Bat loi input tu nguoi dung  
        if(svDAO.ThemSinhVien(a)==-1)
        {
            JOptionPane.showMessageDialog(null, "Format ngày sinh yyyy/mm/dd!\nMSSV không được trùng!\nMã lớp phải tồn tại!", "Sai dữ liệu đầu vào!",
                    JOptionPane.WARNING_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog (null, "Thêm thành công sinh viên "+ txtHoTen.getText());
            
        //Load lai data sau khi them sinh vien
        LoadData();
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnReLoad;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaLop;
    private javax.swing.JCheckBox checkboxNam;
    private javax.swing.JCheckBox checkboxNu;
    private javax.swing.JMenuItem itemDangXuat;
    private javax.swing.JMenuItem itemThoat;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbMSSV;
    private javax.swing.JLabel lbMaLop;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbSoLuongSV;
    private javax.swing.JLabel lbTTSV;
    private javax.swing.JLabel lbThongTinSV;
    private javax.swing.JTable tableSV;
    private javax.swing.JTextPane txtEmail;
    private javax.swing.JTextPane txtHoTen;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextPane txtNgaySinh;
    private javax.swing.JTextField txtSoLuongSV;
    // End of variables declaration//GEN-END:variables
}
